version: '3.8'

services:
    php:
        healthcheck:
            test: [ "CMD", "service", "nginx", "status" ]
            interval: 5s
            timeout: 5s
            retries: 5
        build: .docker/php
        ports:
            - "5173:5173"
        volumes:
            - .:/var/www:cached
    nginx:
        healthcheck:
            test: ["CMD", "service", "nginx", "status"]
            interval: 5s
            timeout: 5s
            retries: 5
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    db:
        healthcheck:
            test: [ "CMD", "service", "nginx", "status" ]
            interval: 5s
            timeout: 5s
            retries: 5
        image: mariadb
        ports:
            - "666:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: book_manager
            MYSQL_USER: tropical
            MYSQL_PASSWORD: pass
