@startuml database diagram

    entity "User" {
        * id : Int
        --
        * name : String
        * mail : String
        * password : String
        remember_token : String
        email_verified_at : Timestamp
        created_at : Timestamp
        updated_at : Timestamp
    }

    entity "Group" {
        * id : Int
        --
        * creator_id : Int
        * name : String
    }

    entity "Book" {
        * id : Int
        --
        * title : String
        description : String
        picture_path : String
        isbn : String
    }

    entity "Review" {
        * id : Int
        --
        * user_id : Int
        * book_id : Int
        * review_amount : Int
        review_content : String
        is_public : Boolean
        created_at : Timestamp
        updated_at : Timestamp
    }

    entity "User_Book" {
        * id : Int
        --
        * user_id : Int
        * book_id : Int
        created_at : Timestamp
        updated_at : Timestamp
    }

    entity "Book_Group" {
        * id : Int
        --
        * group_id : Int
        * book_id : Int
        created_at : Timestamp
        updated_at : Timestamp
    }

    entity "User_Group" {
        * id : Int
        --
        * group_id : Int
        * user_id : Int
        created_at : Timestamp
        updated_at : Timestamp
    }

    entity "Review_Group" {
        * id : Int
        --
        * group_id : Int
        * review_id : Int
        created_at : Timestamp
        updated_at : Timestamp
    }

    "User" }--o "User_Book" : 0..*
    "User_Book" }--o "Book" : 0..*
    "Book" }--o "Review" : 0..*
    "User" }--o "Review" : 0..*

    "User" }--o "User_Group" : 0..*
    "User_Group" }--o "Group" : 0..*

    "Book" }--o "Book_Group" : 0..*
    "Book_Group" }--o "Group" : 0..*

    "Review" }--o "Review_Group" : 0..*
    "Review_Group" }--o "Book_Group" : 0..*

@enduml
